import team02.project.util.Parameters;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Parameters.setNumProcessors(2);

    }
}
